### ISSUE TITLE
The "path" argument must be of type string.

### ISSUE THREAD

**Issue by bluefire2121** [mkosir/react-parallax-tilt#7]
### 🐛 Issue/Bug Report Template

**Describe the bug**  
There's an error in typescript. 

**To Reproduce**  

1. npm install react-parallax-tilt
2. start app
3. see error

**Expected behavior**  
App loads and works

**Code snippets**  

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:372:7)
    at noopServiceWorkerMiddleware (C:\Users\dmsimmon\git-repo\erportal\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\Users\dmsimmon\git-repo\erportal\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:\Users\dmsimmon\git-repo\erportal\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (C:\Users\dmsimmon\git-repo\erportal\node_modules\express\lib\router\layer.js:95:5)`

**Environment**

- Browser: All
- Version: "react-parallax-tilt":
- ...

**Additional context**  
With typescript definitions I believe this error will go away.

**Comment by bluefire2121** [comment]
I think I got this error after running "npm audit fix". The package had over 840 **moderate** vulnerabilities.

**Comment by bluefire2121** [comment]
Anyone else looking at this issue. This seems related to react-scripts. Needed to update react-scripts from 3.3.0 to 3.4.0
